pool:
  vmImage: 'macOS-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    npm install
    cd android
    echo "org.gradle.java.home=$JAVA_HOME" >> ./gradle.properties
  displayName: 'Android Setup Script'

- task: Gradle@3
  inputs:
    workingDirectory: 'android/'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    sonarQubeRunAnalysis: false
    tasks: 'assembleDebug'
